name: myapp
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.1.5

  go_router: ^15.1.2

  sqflite: ^2.4.0
  path_provider: ^2.1.5
  path: ^1.9.1

  sqflite_common_ffi: ^2.3.4+1

  country_state_city_picker: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
